import 'dart:io';
import '../models/key_config_models.dart';
import '../utils/log_service.dart';
import '../utils/key_placeholder_parser.dart';
import 'game_path_service.dart';

/// autoexec.cfg 文件管理服务
class AutoexecService {
  final GamePathService _gamePathService = GamePathService();
  
  /// 配置块标记
  static const String configStartMarker = '# ==== ZEDBOX_CONFIG_START';
  static const String configEndMarker = '# ==== ZEDBOX_CONFIG_END';

  /// 获取 autoexec.cfg 文件路径
  Future<String?> getAutoexecPath() async {
    return _gamePathService.getAutoexecPath();
  }

  /// 检查游戏路径是否已配置
  Future<bool> hasGamePath() async {
    return _gamePathService.hasGamePath();
  }

  /// 尝试自动检测并保存游戏路径
  /// 返回是否成功检测到路径
  Future<bool> tryAutoDetectAndSave() async {
    return _gamePathService.tryAutoDetectAndSaveGamePath();
  }

  /// 读取文件内容
  Future<String?> readContent() async {
    try {
      final path = await getAutoexecPath();
      if (path == null) {
        LogService.w('[AutoexecService] 游戏路径未配置');
        return null;
      }

      final file = File(path);
      if (!await file.exists()) {
        LogService.d('[AutoexecService] autoexec.cfg 文件不存在: $path');
        return null;
      }

      final content = await file.readAsString();
      LogService.d('[AutoexecService] 读取 autoexec.cfg 成功，长度: ${content.length}');
      return content;
    } catch (e) {
      LogService.e('[AutoexecService] 读取 autoexec.cfg 失败', e);
      return null;
    }
  }

  /// 保存文件内容
  Future<bool> saveContent(String content) async {
    try {
      final path = await getAutoexecPath();
      if (path == null) {
        LogService.w('[AutoexecService] 游戏路径未配置');
        return false;
      }

      final file = File(path);
      
      // 确保目录存在
      final dir = file.parent;
      if (!await dir.exists()) {
        await dir.create(recursive: true);
      }

      await file.writeAsString(content);
      LogService.i('[AutoexecService] 保存 autoexec.cfg 成功');
      return true;
    } catch (e) {
      LogService.e('[AutoexecService] 保存 autoexec.cfg 失败', e);
      return false;
    }
  }

  /// 创建文件
  Future<bool> createFile() async {
    try {
      final path = await getAutoexecPath();
      if (path == null) {
        LogService.w('[AutoexecService] 游戏路径未配置');
        return false;
      }

      final file = File(path);
      
      // 确保目录存在
      final dir = file.parent;
      if (!await dir.exists()) {
        await dir.create(recursive: true);
      }

      // 创建空文件
      await file.writeAsString('// CS2 autoexec.cfg\n// Generated by BakaBox\n\n');
      LogService.i('[AutoexecService] 创建 autoexec.cfg 成功');
      return true;
    } catch (e) {
      LogService.e('[AutoexecService] 创建 autoexec.cfg 失败', e);
      return false;
    }
  }

  /// 检查文件是否存在
  Future<bool> fileExists() async {
    final path = await getAutoexecPath();
    if (path == null) return false;
    return File(path).exists();
  }

  /// 解析配置块
  List<ConfigBlock> parseConfigBlocks(String content) {
    final blocks = <ConfigBlock>[];
    final lines = content.split('\n');
    
    String? currentConfigId;
    String? currentConfigName;
    String? currentBindKey;
    final currentContent = StringBuffer();
    bool inConfigBlock = false;

    for (int i = 0; i < lines.length; i++) {
      final line = lines[i];
      
      // 检查配置块开始
      // 格式: # ==== ZEDBOX_CONFIG_START:configId:bindKey ====
      final startMatch = RegExp(
        r'# ==== ZEDBOX_CONFIG_START:([^:]+):([^\s]+)'
      ).firstMatch(line);
      
      if (startMatch != null) {
        inConfigBlock = true;
        currentConfigId = startMatch.group(1);
        currentBindKey = startMatch.group(2);
        currentConfigName = null;
        currentContent.clear();
        currentContent.writeln(line);
        continue;
      }
      
      // 解析配置名称（格式: # 配置名称 - 绑定到 xxx 或 # 配置名称 - 自动应用）
      if (inConfigBlock && currentConfigName == null) {
        final nameMatch = RegExp(r'^# (.+?) - (绑定到|自动应用)').firstMatch(line);
        if (nameMatch != null) {
          currentConfigName = nameMatch.group(1);
        }
      }
      
      // 检查配置块结束
      // 格式: # ==== ZEDBOX_CONFIG_END:configId ====
      final endMatch = RegExp(
        r'# ==== ZEDBOX_CONFIG_END:([^\s]+)'
      ).firstMatch(line);
      
      if (endMatch != null && inConfigBlock) {
        currentContent.write(line);
        
        if (currentConfigId != null) {
          final keyBindings = <String, String>{};
          if (currentBindKey != null && currentBindKey != 'AUTO') {
            // 旧格式：单个按键绑定
            keyBindings['default'] = currentBindKey;
          }
          
          blocks.add(ConfigBlock(
            configId: currentConfigId,
            configName: currentConfigName,
            content: currentContent.toString(),
            keyBindings: keyBindings,
            isManaged: true,
          ));
        }
        
        inConfigBlock = false;
        currentConfigId = null;
        currentConfigName = null;
        currentBindKey = null;
        currentContent.clear();
        continue;
      }
      
      // 添加行到当前块
      if (inConfigBlock) {
        currentContent.writeln(line);
      }
    }

    return blocks;
  }

  /// 添加配置块
  /// 
  /// [content] 当前文件内容
  /// [configId] 配置ID
  /// [configScript] 配置脚本内容（可能包含占位符）
  /// [keyBindings] 按键绑定映射
  /// [configName] 配置名称（用于注释）
  String addConfigBlock(
    String content,
    String configId,
    String configScript,
    Map<String, String> keyBindings, {
    String? configName,
  }) {
    // 先移除已存在的同ID配置块
    content = removeConfigBlock(content, configId);
    
    // 替换占位符
    final processedScript = KeyPlaceholderParser.replace(configScript, keyBindings);
    
    // 生成按键标识（用于标记）
    final keyLabel = keyBindings.isNotEmpty 
        ? keyBindings.values.first 
        : 'AUTO';
    
    // 构建配置块
    final buffer = StringBuffer();
    buffer.writeln('$configStartMarker:$configId:$keyLabel ====');
    
    if (configName != null) {
      if (keyBindings.isNotEmpty) {
        buffer.writeln('# $configName - 绑定到 ${keyBindings.values.join(", ")}');
      } else {
        buffer.writeln('# $configName - 自动应用');
      }
    }
    
    buffer.writeln('# 自动生成于 ${DateTime.now().toLocal()}');
    buffer.writeln();
    buffer.writeln(processedScript);
    buffer.writeln();
    buffer.write('$configEndMarker:$configId ====');
    
    // 添加到文件末尾
    if (content.isNotEmpty && !content.endsWith('\n')) {
      content += '\n';
    }
    content += '\n${buffer.toString()}\n';
    
    return content;
  }

  /// 移除配置块
  String removeConfigBlock(String content, String configId) {
    final lines = content.split('\n');
    final result = <String>[];
    bool inTargetBlock = false;
    
    for (final line in lines) {
      // 检查是否进入目标配置块
      if (line.contains('$configStartMarker:$configId:')) {
        inTargetBlock = true;
        continue;
      }
      
      // 检查是否离开目标配置块
      if (line.contains('$configEndMarker:$configId')) {
        inTargetBlock = false;
        continue;
      }
      
      // 不在目标块内，保留该行
      if (!inTargetBlock) {
        result.add(line);
      }
    }
    
    // 清理多余的空行
    return _cleanupEmptyLines(result.join('\n'));
  }

  /// 清理多余的空行（连续超过2个空行的情况）
  String _cleanupEmptyLines(String content) {
    return content.replaceAll(RegExp(r'\n{3,}'), '\n\n');
  }

  /// 检查配置是否已应用
  bool isConfigApplied(String content, String configId) {
    return content.contains('$configStartMarker:$configId:');
  }

  /// 获取已应用配置的按键绑定
  String? getAppliedKeyBinding(String content, String configId) {
    final match = RegExp(
      '$configStartMarker:${RegExp.escape(configId)}:([^\\s]+)'
    ).firstMatch(content);
    
    if (match != null) {
      final key = match.group(1);
      return key == 'AUTO' ? null : key;
    }
    return null;
  }

  /// 在文件管理器中打开
  Future<void> openInExplorer() async {
    try {
      final path = await getAutoexecPath();
      if (path == null) {
        LogService.w('[AutoexecService] 游戏路径未配置');
        return;
      }

      final file = File(path);
      final dir = file.parent;
      
      if (Platform.isWindows) {
        await Process.run('explorer', [dir.path]);
      } else if (Platform.isMacOS) {
        await Process.run('open', [dir.path]);
      } else if (Platform.isLinux) {
        await Process.run('xdg-open', [dir.path]);
      }
      
      LogService.d('[AutoexecService] 打开文件管理器: ${dir.path}');
    } catch (e) {
      LogService.e('[AutoexecService] 打开文件管理器失败', e);
    }
  }
}
